# Authors and Contributors {.unnumbered}

This book is the result of a broad community of vascular surgeons and trainees. They have all freely donated their time to contribute to this work and we owe them a debt of gratitude. Follow them on twitter or other social media platforms to keep up to date with what they have going on.

**Danielle Bajakian, MD;** Assistant Professor of Vascular Surgery; Director, Critical Limb Ischemia Program; *Columbia University, New-York Presbyterian*

**Mohamed Barkat, MSc, FRCS (Vasc);** Consultant Vascular Surgeon; *Manchester University NHS Foundation Trust;* [\@mo_barkat](https://twitter.com/mo_barkat)

**Einar Brevik, MD;** Consultant Vascular Surgeon; *Haukeland University Hospital*

**Sarah J. Carlson, MD, MSc, FACS;** Professor of Vascular Surgery, Associate Chief for Surgery Operations; *Boston University, Boston VA Medical Center;* [\@sarahcarlsonmd](https://twitter.com/sarahcarlsonmd?lang=en)

**Marlin "Wayne" Causey, MD;** Chief of Vascular Surgery; *Brooke Army Medical Center*

**Matthew Chia, MD, MS**; Vascular Surgery Resident; *Northwestern*; [\@chia_md](https://twitter.com/chia_md?lang=en)

**Anahita Dua, MD, MS, MBA, FACS;** Assistant Professor of Vascular Surgery; Director of Vascular Laboratory; Co-director of the Peripheral Arterial Disease Center; *Harvard University, Massachusetts General Hospital;* [\@AnahitaDua](https://twitter.com/anahitadua)

**Julie Duke, MD, RPVI;** Vascular Surgeon; *Vascular Surgical Associates of Atlanta, GA*

**Matthew Edwards, MD;** Richard H. Dean Professor and Chairman of Vascular and Endovascular Surgery; *Atrium Health Wake Forest Baptist;* [\@msedwards0427](https://mobile.twitter.com/msedwards0427)

**Sharif Ellozy, MD;** Associate Professor of Vascular Surgery, Vascular Surgery Fellowship Program Director; *Weill Cornell Medical College, New-York Presbyterian;* [\@SharifEllozy](https://twitter.com/sharifellozy)

**Adham Elmously, MD**; Cardiothoracic Surgery Fellow; *Houston Methodist;* [\@elmouslyMD](https://twitter.com/elmouslymd?lang=en)

**Leanna Erete, MBBS;** Vascular Surgery Trainee; *London Deanery;* [\@leanna_erete](https://twitter.com/leanna_erete?lang=en)

**Alex Forsyth, MD;** Vascular Surgery Resident; *University of Massachusetts;* [\@alex_forsyth\_](https://twitter.com/alex_forsyth_)

**Rachael Forsythe, MBChB, PhD**; Consultant Vascular Surgeon; *Royal Infirmary Edinburgh;* [\@ROForsythe](https://twitter.com/roforsythe?lang=en)

**Nicholas Greaves MBChB, PhD, FRCS (Vasc);** Consultant Vascular Surgeon; *Manchester University NHS Foundation Trust*

**Manj Gohel, MBChB, MD, FRCS, FEBVS;** Consultant Vascular Surgeon; *Nuffield Health;* [\@ManjGohel](https://twitter.com/manjgohel)

**Eilidh Gunn, MBChB, MRCSEd;** Clinical Research Fellow, Vascular Surgery; *Royal Infirmary Edinburgh;* [\@eil1_g](https://twitter.com/eil1_g)

**Michael Jenkins, BSc, MBBS, MS, FRCS, FEBVS;** Consultant Vascular Surgeon; *St Mary's Hospital, Imperial College Healthcare NHS Trust and Chelsea and Westminster Hospitals;* [\@mpj21165](https://mobile.twitter.com/mpj21165)

**Adam P. Johnson, MD, MPH;** Consultant Vascular Surgeon; *Royal Infirmary Edinburgh;* [\@adam_mdmph](https://twitter.com/adam_mdmph?lang=en)

**Nedal Katib, MB, BCh, BAO, MS, FRACS;** Consultant Vascular Surgeon; *Prince of Wales Hospital, Gosford and Wyong Hospitals*

**MAJ Kevin Kniery, MD, MPH;** Vascular Surgeon; *Brooke Army Medical Center;* [\@Kniery_Bird](https://twitter.com/kniery_bird)

**Young Lee, MD;** Vascular Surgery Fellow; *Emory University;* [\@youngclee86](https://twitter.com/youngclee86)

**Joseph Lombardi, MD, MBA;** Professor and Chief of Vascular Surgery; *Cooper University Hospital;* [\@VascSurgMD](https://twitter.com/vascsurgmd)

**Rafael Demarchi Malgor, MD, MBA, FACS;** Associate Professor of Surgery; Program Director, Robert B. Rutherford fellowship and residency in Vascular Surgery; Division of Vascular Surgery and Endovascular Therapy; *The University of Colorado, Anschutz Medical Center;* [\@RafaMalgor](https://twitter.com/rafamalgor)

**M. Asharf Mansour, MD;** Academic Chair, Vascular Surgeon; *Michigan State University, Spectrum Health*

**Nicolas J Mouawad, MD, MPH, MBA, FSVS, FRCS, FACS, RPVI;** Chief and Medical Director of Vascular and Endovascular Surgery; *McLaren Health System - Bay Region, Michigan, USA*; Associate Clinical Professor of Surgery, *Michigan State University, Central Michigan University*; [\@NickMouawadMD](https://twitter.com/nickmouawadmd?lang=en)

**Cullen McCarthy, MD;** Vascular Surgeon; *Cardio-Thoracic & Vascular Surgical Associates, Mobile Infirmary*

**Mia Miller, MD;** Resident; *University of Minnesota*

**Andrew Nickinson, MBBS, MD, MRCS(Eng);** Vascular Surgery Trainee; *Wessex/Thames Valley Deanery* [\@AndrewNickinson](https://twitter.com/andrewnickinson)

**Anna Ohlsson, MD;** Assistant Professor of Surgery, Associate Program Director for Vascular Surgery training programs; *University of Pennsylvania,* *Corporal Michael J. Crescenz/Philadelphia VA Medical Center*

**Alaska Pendleton, MD, MPH;** Vascular Surgery Resident; *Massachusetts General Hospital*

**Todd Rassmussen, MD;** Professor of Surgery, Vice-Chair of education; *Mayo Clinic;* [\@trasmussen_md](https://mobile.twitter.com/trasmussen_md)

**Nicole Rich, MD, MPH;** Vascular Surgeon; *Ascension Medical Group Saint Thomas Rutherford Surgery*

**Drena Root;**Vascular Center Technical Director; *Massachusetts General Hospital*

**Nakia Sarad, DO, MS;** General Surgery Resident; *New York Presbyterian/Queens - Weill Cornell*

**Sherene Shalhub, MD;** Associate Professor of Surgery, Division of Vascular Surgery; *University of Washington;* [\@shereneshalhub](https://twitter.com/shereneshalhub)

**Kush J Sharma, MD, RPVI;** Vascular Surgeon; *Desert Vein and Vascular Institute*

**Sammy Siada, DO, RPVI;** Assistant Clinical Professor of Vascular and Endovascular Surgery; *UCSF Fresno;* [\@SammySiada](https://twitter.com/sammysiada)

**Aminder Singh, MBBS, MRes, MRCS;** Vascular Surgery Trainee, PhD Candidate; *East of England, University of Cambridge;* [\@AminderASingh](https://twitter.com/aminderasingh)

**Matthew R. Smeds, MD, FACS, DFSVS;** Professor of Surgery, Division of Vascular and Endovascular Surgery; *St Louis University*; [\@mattsmeds](https://twitter.com/mattsmeds?lang=en)

**Matthew Smith, MD, PhD;** Assistant Professor of Surgery, Division of Vascular Surgery; *University of Washington*

**Matt Spreadbury, MD;** Vascular Surgery Resident; *Haukeland University Hospital*
