# Preface {.unnumbered}

Version - DRAFT

Editors: Editors: Adam P Johnson MD, MPH; Matt Smith MD, PhD; and [Audible Bleeding Team](https://www.audiblebleeding.com/about-1/).

This content was developed by the [Audible Bleeding Team](https://www.audiblebleeding.com/about-1/) to accompany our board review podcast series. Each chapter covers a key domain of vascular surgery, essential for board review preparation, and is associated with an Audible Bleeding episode which you can access through the link embedded into the text.

## Usage

This e-book is not intended to be a comprehensive board review guide, but instead serves as an easily accessible resource, paired with our podcast content to help streamline exam preparation.

Please consider this a "living document." We plan to post regular updates and respond to your feedback. We are utilizing an open source annotations software called [hypothes.is](https://web.hypothes.is) to allow you to take note along side our e-book. Feel free to post your notes publically if you think other readers would benefit from your additions, or create a small private group for your local trainees of faculty members. We will work to incorporate relevant notes and additions into future editions.

## Comments, Questions or Contributions

Please visit our [github page](https://github.com/adam-mdmph/vs-examprep) or [send us an email](mailto:audiblebleeding@vascularsociety.org).

```{r include=FALSE}
knitr::write_bib(c(
  .packages(), 'bookdown', 'knitr', 'rmarkdown', 'embedr'
), 'packages.bib')
```
