# Aneurysms - Thoracic and Thoracoabdominal

02 Dec 2021: Rachael Forsythe, Mr. Mohamed Barkat, Mr. Nick Greaves, and
Mr. Michael Jenkins

```{r echo=FALSE}

library (embedr)

embed_audio("https://traffic.libsyn.com/audiblebleeding/Rouleaux_Club_TAA_Studio_sound_version_11-17-21_Auphonic.mp3")

```

## Anatomy and Demographics

**Can you take us through the Crawford classification to start off?**

The Crawford classification is relatively recent, to be honest it was
1986.[@crawford1986] And I think it was really important because it's
very practical classification, depending on body cavity and how to get
to an aneurysm. It's a bit old in terms of anatomy because they don't
really follow a pattern one would expect going one to four would be
getting either more extensive or less extensive. And it's not quite like
that.

So type one is from the left subclavian down to just below the
diaphragm. And that's crucial because that distinguishes it from a
thoracic aneurysm, which you can get to just from the chest and from a
practical surgical approach. That's a very important differentiating
marker, but you have to go into a second cavity.

Type two is the biggie. So this is from the left subclavian all the way
down to your bifurcation. So both abdominal and thoracic exposure, all
the visceral, renal arteries and a lot of intercostal and lumbers. So
big impact for cord supply, et cetera.

So three is for mid chest down to and involving the viscera, renals, and
bifurcation. And that's the one, which really is I suppose, the
differentiator between whether you go for the full support that's needed
in a type two, or whether you can risk a clamp and go approach.

And type four is characterized by being in most patients accessible from
the abdomen. I say in most patients, because there are some anatomical
situations with body habitus, which means that going into the left chest
is useful even for type four aneurysm.

Then type five. It was an additional classification that came in later,
which is a bit like a type three at the top of the type one at the
bottom effectively, but not everyone uses that.

**There appears to have been an increase in the incidence of
thoracoabdominal aneurysms. Do you think it's a true increase or does
this relate to having scans for other reasons picked up by accident and
then going on from that? What sort of many referrals do you get in a
year and what's your turn down?** **How many numbers are you actually
doing in your practice year on year?**

So that's interesting because the overall incidence of infrarenal
atherosclerotic aneurysms is going down every year in the national UK
vascular registry. And I suppose that is a legacy of the end of smoking
for a big group of patients. I think thoracoabdominal aneurysms are
going up partly because we are now imaging more and more people. and
therefore we are imaging the chest and seeing them, which perhaps wasn't
the case, previously. So that's an artificial increase in incidence, but
also the rate of aortic dissection is on the rise, s chronic post
dissection aneurysms are increasing. I think it's a small group, but
there is more knowledge about connective tissue disease and genetic
studies and family screening, which perhaps is also a small part of
annual increase. So over the next, 10, 20 years, certainly aneurysms are
not going to go away. And that group of patients that have been affected
are still around and there is a huge number now within the national UK
screening program under surveillance for small animism, so it will come
to fruition.

### Etiology

**You've just touched on a bit of difference in the etiology between
thoracoabdominal aneurysms and abdominal aortic aneurysm. So is there a
huge difference in the etiology between these two type of aneurysm from
your experience?**

On presentation, the majority of aneurysms are asymptomatic. So they're
found incidentally. It is rare that you get a symptomatic aneurysm. Some
can get tender as they approach a time when the wall is going to breach
pre rupture. I think thoracoabdominal aneurysms tend to be a bit more
symptomatic than infrarenal. These are ones that go into the arch and
present with hoarseness from recurrent laryngeal tension or bronchial
compression.

There is a group that cause dilatation of the crus\--I've seen, the crus
of the diaphragm acts like an extrinsic wrap and it can be extremely
tight at that point. These patients present with excruciating pain,
radiating around their cost al margin. This is tension on the crus and
it's often not thought of as a sign of of an aneurysm, but I think in
that group, it is. The larger the extent of aneurysm, things like weight
loss and general poor health begins to become increasingly seen in that
group with chronic aneurysms. So there are some subtle differences.

The other group that tends to occur, not in infrarenal aneurysms, is the
post dissection aneurysms and the majority of those are known about. But
there was a time when type A dissections, as in Stanford type one, which
went all the way down were only monitored really with echo and the
ascending. The rest was forgotten about, they got lost from
cardiothoracic follow up. That group is a different group because we
already know they've got an aneurysm. So there are subtle differences.

And then the connective tissue group, I suppose, is a bit different
because they tend to have more extensive aneurysms rather than just
confined to the infrarenal segment, which is by far and way, the most
common for abdominal aneurysms.

**So you've mentioned a few different etiologies. Moving on to
specifically thoracic aneurysms, you said a quarter of these are
associated with dissection in the past, and a small portion will have
underlying connective tissue disease. Do you think these patients will
have a different threshold for intervention compared to the
non-connective tissue disorder patients?**

I think we need to be aware that the connective tissue disorders we talk
about---Marfan's, Loeys Dietz, vascular Ehlers Danlos---are probably the
tip of the iceberg of a number of other cases that we don't have genetic
sequencing for, but behave differently. The data from a dimention point
of view is not quite as robust as one would hope, but the threshold that
most people would agree for non connective tissue disorders would be
about six centimeters. That takes into account the increased risks of
operating both in the chest and the abdominal segment.

I think most people would agree that five centimeters is a better cutoff
for connective tissue patients. Some cardiac surgeons would repair a
young Marfan ascending aneurysm at four and a half centimeters. It does
vary a little bit geographically, a bit like the threshold for
infrarenal aneurysms, which varies between Europe, the States and the
UK. So you've got to look at the patient in front of you and make a
decision. I would certainly increase the threshold for someone who was
not so fit and perhaps lower it a bit for a younger patient.

Also, be aware if it's something odd anatomically---a saccular bulge,
something where you think there could be a mycotic element---those are
all very different you can't be reassured by a dimension in an axial
plane that is safe. These findings up the ante, in terms of whether you
would pair at an earlier threshold. I'd include there a blowout for an
eccentric penetrating aortic ulcer (PAU) or anything like that, which is
not a conventional fusiform aneurysm.

**Can you talk us through the Ishimaru zones of the aorta and why do we
need to know about these?**

Ishimaru was one of those useful classifications, there's lots of
classifications in medicine, but it's nice to find one that's actually
got a use. This classification made sure that everyone was on the same
page when reporting seals zones for thoracic devices. That is important
for two reasons. 1) the extent of coverage and 2) the complications
increased, the more proximally you go. The main complication for that is
stroke. So historically, Ishimaru decided to classify these zones.

-   **Zone 0**, the first most proximal zone, is the ascending aorta up
    to and including the brachiocephalic trunk

-   **Zone 1** is between the brachiocephalic trunk and including the
    left common carotid artery

-   **Zone 2** is between the left common carotid artery and including
    the left subclavian artery

-   **Zone 3** is the aortic segment just distal to the left subclavian
    artery.

-   **Zone 4**, added by some people, is distal to the T4 level, which
    is much lower down the thoracic aorta

Most thoracic stenting will go really to zone three or perhaps into zone
two. The more proximal you go, the more work needs to be done in terms
of either extra anatomical debranching or using some form of fenestrated
or branched arch device with an increase in stroke risk. What this
allowed people to do is compare different series. You're not just saying
these were a group of TIVA patients, but you could define exactly how
proximally they go.

And the same applies for the Crawford classification. It allows
comparison within thoracoabdominal groups, and that's important with
both survival and complication rates. Because if your series is mainly
extent 2 thoracoabdominal aneurysms, you're going to have a very
different outcomes from someone who's got mainly type four aneurysms.
Both classifications allow you to look at and compare data between
groups.

## Management

### Ascending aorta and arch

**So if a patient has a thoracic aneurysm that affects their ascending
aorta, we obviously involve the cardiac surgeons. The patient may
require an elephant trunk procedure prior to intervention on the
descending aorta. Can you briefly summarize the difference between a
conventional elephant trunk and a frozen elephant trunk, and when to use
one over the other?**

This is particularly pertinent to aortic dissection. The the main
purpose of repair in Type A dissection is to protect the heart. People
die of either rupture into pericardium causing tamponade or stripping
the coronary ostia off and getting myocardial ischemia. So the priority
of repair in acute ascending aortic dissection is primarily to protect
the heart and to some extent for ensure a true lumen flow distally.
Therefore, it was very popular because it was the least invasive to do a
short interposition ascending repair, but that really left problems for
later.

Therefore, as people became more adept with cardiac and cerebral
protection, it became more popular to do a more extensive repair in the
first sitting. This involves an arch repair and an acceptance that
eventually the descending thoracic aorta will still need to be repaired,
but at a later stage. Now you have to be aware that the ascending and
arch is done from a median sternotomy, and it's really difficult to get
beyond the left subclavian form that position.

So when the arch was done, it was felt that the elephant trunk came from
leaving an extra piece of dacron within the descending thoracic aorta in
the true lumen of a dissection or in the main lumen of an aneurysm by a
double sewing technique on the distal anastomosis and an inverting it.
It would be left free and perfused in the descending, thoracic aorta.
The benefit of that was when one came back to then do the descending
thoracic segment via left thoracotomy, you could very quickly open the
aorta and clamp that Dacron for a ready, made proximal anastomosis,
which was much easier. It meant you didn't have to grow up and dissect
to the left subclavian with scar tissue and a previous anastomosis.

Now, what industry realized is that they could help with this procedure
by actually facilitating a device which had three or four branches on a
piece of Dacron, which was sized to be an arch replacement. There were
ready-sewn 10 millimeter branches with an extra pipe for rewarming.
These could then be sewn to be a innominate, carotid and subclavian and
attached to that piece of Dacron was then a stent graft, which could
then be placed distally in lieu of what was previously a floppy piece of
Dacron.

And two manufacturers, JOTEC and Terumo Aortic, have made these devices,
which facilitate and make things much easier. Therefore, so-called FET
or frozen elephant trunk, has now become quite popular. I don't quite
know why it's called frozen, but I think it perhaps means that the
thoracic segment is stiff with a supported stent graft rather than just
a floppy Dacron segment.

### Isolated Thoracic Aneurysms

**So if we look at it at the isolated thoracic aneurysm, can you tell us
briefly about the principle of TEVAR and what's the optimal landing
zone. Finally, in your opinion, is rapid ventricular pacing required
when deploying these stents?**

So I think the isolated, thoracic aneurysm is a perfect application for
TEVAR because it fulfills all those minimally invasive credentials---an
endoluminal approach and if you can get a good seal zone, proximally and
distally, it saves a thoracotomy and it's a massive difference for the
patients. Unfortunately I suppose those cartoons you see on the industry
advertisements are vanishingly rare, when you've got a perfect proximal
and distal landing zone and have really straight thoracic aorta.

I think for the majority of cases, you need a 2cm seal zone proximally
and distally. However, if you have a torturous aorta, you likely need a
longer seal zone. You want to land in an area where there is a good
parallel walled walled segment. You have to be careful of so-called
"bird-beaking" when a stiff, less conformable device lands perfectly on
the outer curve, but holds off on the inner curve. This resultsin a lip,
which protrudes and allows blood to get under that and cause stent graft
crushing. I think modern devices have become much more conformable.
We've learned the lessons of oversizing and the problems associated with
oversizing. We've learned how to taper stent grafts when there's
mismatch between proximal and distal landing zones.

These have all significantly improved things, but there's still no
getting away from the fact that some anatomy is not well adjusted to the
currently available stent grafts and Gothic arches are a particular
problem. I've already mentioned torturous and large sacks, which allow a
stent graft to move away from the center line to the outter
curve.[@iwakoshi2019] If that sac doesn't shrink, you can imagine that
draws on both the proximal and distal seals zone, and reduces them.

I think you can sometimes get away with a shorter landing zone. If, for
example, you're doing a post traumatic aneurysm where it's only on one
segment of the outer wall where there's a problem. But for the vast
majority of true aneurysms, you need that seal zone and you do need to
oversize to achieve that.

You can go more proximally, and I think the majority of aneurysms at the
left subclavian area, you can just drop the blood pressure to a systolic
of 70 or 80 pharmacologically. Once you go more proximal to that,
especially if you've got a custom device, with a scallop or branched
device where you need an absolutely critical landing zone, you then
really need to achieve a short transient period of circulatory arrest,
either with adenosine, which is perhaps sometimes a bit unreliable, or
rapid pacing.

Rapid Pacing can be difficult and does come with complications though,
such as ventricular puncture. There are some newer techniques in terms
of caval occlusion balloons, which basically stop venous blood returning
to the heart with a reduction in output. Those are gaining popularity
certainly in Germany and they can be quite effective for that. I think
having tip capture on devices and better, more accurate deployment and
better imaging does allow you to be more accurate in deployment, but
there are still problems.

These devices have been inserted to very torturous iliac systems
sometimes and they retain some energy. When you deliver them by removing
that sheath, sometimes that energy is still there and they can jump
forward as well as back. This can cause problems because you end up
covering a vessel that you didn't intend to.

**So you've just explained in detail that TEVAR is a great option for
the majority of cases, but I presume you still believe there is a place
for open repair in isolated, thoracic aneurysms, and why?**

I'm not so sure in isolated, thoracic aneurysms, unless for some reason
they're not suitable for TEVAR. I think if you've got problems with a
mycotic aneurysm or a fistula into the bronchus or esophagus, these are
our big problems with high mortality and your duty bound to go for open
repair.

Patients with hemoptysis and a previous aortic repair should carry a
high suspicion for an aortobronchial fistula. TEVAR is considered
preferred repair, due to high morbidity and mortality with open repair.
Bronchoscopy should be avoided due to high risk of
rebleeding.[@bailey2011; @léobon2002; @quintana2006]

Certainly with connective tissue patients, open has advantages. In some
unique situations it is possible to bridge between repairs. I think in
some of the younger connective tissue patients, they will end up having
certain segments repaired at different stages of their life. Although
it's probably now accepted that "all endovascular" is not a good option
for these patients, if you've got Dacron proximally and distally
already, bridging those segments with an endovascular device might work
well. Although the Dacron will slowly dilate, it won't dilate as much as
aortic tissue in these patients. So there are options, but I think in
reality, isolated, thoracic aneurysms on reasonable rare and TEVAR can
be used for the majority of them.

### Thoracoabdominal Aneurysms

**Moving on to thoracoabdominal aneurysms. Earlier we used the Crawford
classification to describe the anatomical extent of the thoracoabdominal
aneurysm. So let's talk firstly, about type 1, 2, 3, and 5, which
involved the thoracic of water to a greater or lesser extent as well as
the abdominal aorta. We'll come back to type four later on in this
podcast.**

**So type 2 open thoracoabdominal aneurysm is arguably the most invasive
operation a patient can undergo and carries 30 day mortality in excess
of 10 to 15%. What is the size threshold for type two that you currently
use in your practice and what is the evidence for this?**

So, as I suggested earlier, the evidence is that it's a bit historical,
and most people would actually say about six centimeters. I think that
can be brought down a little bit for connective tissue patients and can
go up a little bit for atheromatous patients. But in general, you're
talking about a younger segment of patients. This is not an operation
for people in their eighties. Outcomes stratified by age greater than 50
found a higher rate of death, paraplegia, renal failure, cardiac
complications and length of stay.[@coselli2017] These patients need to
be in very good shape because it is a big onslaught physiologically on
them. It's not just getting them off the table, it's getting them out of
intensive care and out of hospital and to recover back to their
baseline.

I think that's one of the things that can be really difficult about this
disease. You are taking patients who are effectively functioning quite
well, and they're often relatively asymptomatic and you're putting them
through a prophylactic operation to try and prevent rupture, which no
one quite knows if or when it'll happen.

**So to that end, can you talk us through the decision making process
when you're assessing a patient with a thoracoabdominal aneurysm types
1, 2, 3, or 5?**

I think it is really dependent on anatomy, physiology, and the patient
in front of you. Unfortunately, it is a bit of a bespoke assessment for
an individual patient. So firstly, I think you have got to look at what
are the options for that patient, which goes from conservative to
endovascular, to open surgery.

The endovascular domain has changed hugely now with the increasing
availability of branched devices. When I started, there weren't custom
devices. There were some FEVAR devices just coming out, and we did use
long covered stents going through devices with TIVA above. However,
there wasn't the option for what we've now got from an endovascular
perspective.

So I think you've got to choose the patients that are either unsuitable
for endovascular, or are we really going to benefit from a durabililty
of an open approach. Those are the two big differences, and they are
differences. One, you're going for gold standard approach because you
think they're life expectancy warrants that. The other one is much
higher risk, because they haven't got another endovascular option. These
range from people with very tortuous anatomy, to difficult renal
arteries, such as early divisions, that make them unsuitable as target
vessels. Another reason is complex dissections, which are not suitable
for an endovascular approach. Therefore, it is quite variable, but the
first thing you must consider is whether this patient is going to get
through this and get out of hospital. And that really is looking at them
in the eye and considering what's their quality of life or what's their
family support, and are they up for this?

The second one then is anatomical difficulties--- Is there a shaggy
aorta, atheromatous disease, or calcification of a target vessel, etc.
Severe aortic wall thrombus is associated with solid organ infarction
(24%), acute kidney injury, without dialysis (21%) and dealayed oral
intake by 3.4d, however rarely resulted in mortality
(0.5%).[@ribeiro2017] Rarely is this a hundred percent or 0% decision,
but it's about building up relative contraindications. Some of them are
pretty simple, like access problems for endovascular, and it's a
combination of those which then will sway you in one way or the other.
And if anything, that decision-making is probably more pertinent for
type three and type four, where there really is a different option and
these patients are n their sixties and seventies with classic
atheromatous disease. The really, young fit non-connective tissue
patient with a type 2 TAAA is a rare beast.

**For connective tissue disease, many textbooks prefer an open approach
over an endovascular approach do you still agree with this?**

Yes, I do. I think certainly, what were you know about patients who've
had total endovascular approaches for connective tissue diseases is that
they don't last. They may last five years or so and then you get
progressive aortic dilatation and loss of those of seal zones. Whether
that is the natural history of the native disease or whether it is
regional force hooks, barbs or whatever is related to the device is
unclear.

But when you sew these pensions and just touching the back end of a
needle on the anterior wall can create a massive problem or just being a
little bit clumsy and you get a radial tear. It's very clear that a
stiff device sitting in those aortas for many years with 60-70 beats per
minute going through it and often hypertension, isn't going last.

However there are some caveats, as I mentioned earlier, bridging between
previous prosthetic open repairs is a possibility. And sometimes in a
lifesaving situation, such as when someone has presented with a rupture,
you may have to use an endovascular approach. However, be prepared then
to treat that as a bridge and go back to do a definitive repair when
things have calmed down and in the cold light of day.

**So we don't really have the scope to dive into complex endovascular
repair in this episode, but can you describe the broad principles of
your operative approach to open thoracoabdominal aneurysm repair, type
two, because it's the most extensive?**

In terms of the patient, for anything juxtarenal or type four, I tend to
have a patient supine on their back, but with a break in the table at
the level between the costal margin and the anterior superior iliac
spine. Breaking the table at that level, you can massively increase the
exposure to that segment.

However, there are some patients even with a type four repair that
demand a left thoracoabdominal incion. For a type four, if you're doing
a left thoracoabdominal approach, it's usually for someone with a very
narrow acute angle of the costal margin, such as a more petite frame
female patient or a crus that is very high on the aorta. And if you look
at CT scans, which is something I've realized over many years, that not
everyone is the same. So where the celiac and SMA are can be in a
different proportion, depending on where the costal margin and and
skeleton is, which can make them easier or hard to get to. And certainly
in a situation, if there is a rupture within the left side of the
abdomen, you wouldn't really want to go into that without getting
proximal control. Because as you do the viceral rotation, you could have
catastrophic bleeding.

So under those circumstances, I'd also go into the left chest with a
reasonably low segment so that you can place a clamp ready before doing
the visceral rotation. So for type four the one above then, the higher
you go, the higher your thoracotomy and the more tipped over you need
the patient. So for a type two, you're going probably fifth intercostal
space and the shoulders are at 90 degrees and the pelvis is 60 degrees.
For type three, you're slightly further over, so you're down to about 60
degrees and you're perhaps in the seventh intercostal space. So the
lower you go, then right up to being pretty much supine.

The left arm is put over top. You mark the scapular and you go into the
chest and abdomen. I tend to go intraperitonealy into the abdomen, so I
can see the bowel, although there are people who do a retroperitoneal
approach. I tend to divide the diaphragm down to the central ligament
and mark that. Then effectively you are looking at your clamp zone. You
dissect around your clamp zone, both proximally and distally. We don't
tend to expose the celiac and SMA in particular, or the right renal.
It's important to find the left renal artery. For the visceral rotation,
you effectively extend the left colon up, find the white line and get
under that and get right onto psoas. The key is to get right down on the
psoas early on, and then it is a relatively bloodless field. Everything
has taken me to leave the ureters out of the way. I always take for left
kidney up. You will see in the textbooks and some advocate to keep the
left kidney down. I that's utter madness to be honest and I can't see
any point in it.

So for me, everything rotates up then out of the way. And it it looks a
bit strange, like a postmortem. It looks very odd to see the whole left
side abdominal cavity when all you've got is diaphragm muscle, psoas
muscle and nothing else left. It does give you a very safe exposure then
to the aorta. I don't tend to go round the aorta with slings, I think
that can cause problems. I go around with my fingers and be very aware
of the right sided lumbers or intercostals because you really don't want
to cause a problem there because you easily get into the right chest
from that exposure. So you have to be a bit careful so you can see
exactly where you're getting round.

**So in specifically with a type 2 TAAA, many people establish a left
heart bypass. Do you always operate in that way and do you use a cardiac
surgeon and the setting?**

I think type 2 you are mandated to have some sort of adjunct to keep the
rest of the body perfused while you're doing the proximal anastomosis. I
think in an elective setting left heart bypass is the right way forward,
because it does give you more flexibility and it allows you then to
sequentially clamp and keep the legs, the viscera or the kidneys
perfused. There are some negative aspects to left heart bypass, though,
in terms of needing a much higher ACT and bleeding is the enemy here.
The more you anti-coagulate, the more problems you've got. It's also not
pulsatile flow and you're putting all your cells through a pump and
you've got to be aware of increased problems around stroke and
everything else that goes with that. I think it is very convenient for
that set up, because you can get to the inferior pulmonary vein quite
easily and femoral cannulation is quite easy for you to return and then
you've got the option then of individually calculating celiac and SMA
for perfusion, whereas usually renals are cooled down.

If you've got a perfusionist there as well, you can get cold perfusate
for the renal arteries. So it gives you more flexibility, and if things
go wrong, you've then got an option to switch to conventional bypass if
needed or even drain out and go to circulatory arrest and cool-down.

So it does give you more options, however, in a more emergency setting,
an approach that tends to work quite well for us is to do an ax-fem
approach. You use an ax-fem graft onto the light subclavian artery, not
tunneled but on the outside of a body onto the right femoral and use the
other limb as a single cannula, usually for the SMA, because the SMA is
the king vessel with all of this. Most of the other things can go, but
if you lose the SMA, you've got a dead patient. And that allows you to
do an emergency procedure, a mid type 3 approach, without some of the
problems associated with left heart bypass. It allows you to have a
lower ACT; it gives you pulsatile flow; you're not smashing your cells
up all the time; and it's relatively quick and straightforward to do.
You don't have to mobilize a perfusionist and everything else that goes
with that. It's worked well for us in emergency settings. It's better
than a clamp and go approach because with a clamp and go approach, for
the type 3 repair, you need to complete in 15 minutes, your inlay
anastomosis at the top, the clock is already on. If you get down to the
visceral segment and you've got to do some removal of thrombus to get
your Corolla patch on or you've got to reimplant the left kidney
separately, it's a lot of time pressure and there's no opportunity for
something to go wrong there. That's where this gives you a bit more
breathing space that you've got the lower body perfused while you're
doing your proximal anastomosis.

#### Complications

**As you've mentioned, open repair is a high tariff, high risk
operation, but apart from death, are there any specific complications to
the open approach?**

The big problems are bleeding and clamp times. Those are the things that
cause problems for those patients who survive. So problems with large
transfusion which cause problems with ventilation afterwards. The most
common complications after a TAAA are pulmonary with 8.5% of one cohort
requiring a tracheostomy.[@coselli2016] Renal ischemia is an issue of
people will quote a 40 to 50 minute renal warm ischemic time, you are
then getting increasing problems with likely renal failure. They may
need to go on the hemofilter for temporary support, but these patients
have already lost a lot of nephrons, so they haven't got a huge amount
of capacity to lose more. That's why eGFR or high creatinine is a really
important prognostic marker of outcome in this patients. I think it's
like a barometer on their micro-circulation.

The big one and the Achilles heel of these approaches, whether it's
endovascular or open is spinal cord ischemia and that is because of the
segmental of blood supply to the cord comes from all the intercostals
and lumbers. If you've got that aneurysm extending both proximally and
distally involving the internal iliacs the left subclavian, then you're
taking out your crucial collateral supply. And that is why trying to
maintain blood supply, for example getting the lengths back in circuit
early, whether that's removing the large sheaths, during a long branched
approach or getting the leg supply earlier in an open approach, and
keeping the left subclavian in circuit. These are all other important
things, paying attention to the mean arterial pressure in theater, have
a spinal drain working, all of that is crucial in terms of trying to
protect the cord as much as possible.

Post TEVAR leg weakness needs to undergo urgent evaluation. Differential
diagnosis includes spinal ischemia due to subclavian or intercostal
artery coverage, distal embolization or stenosis of the TEVAR graft.
Stenosis should be treated with angioplasty and extension.[@buth2007]

**So the major issue is the spinal cord ischemia, and we mentioned
briefly the blood supply of the spinal cord for the sake of the exam.
Can you recap for us the blood supply of the spinal cord?**

Soit's complicated actually. There are anterior and posterior spinal
arteries, but I think depending on what level you are in the cord, they
get a blood supply from a more dominant approach. So higher up in the
cord---cervical and higher thoracic---vertebral arteries are important,
so hence the importance of a left subclavian bypass.

The lower you go, then they become a bit less important and the actual
segmental arteries, intercostals, become dominant. Much is talked about
the artery of Adamkiewicz. I think, yes, there may be a dominant vessel
at about that level, but it's rarely one, absolutely single one that if
you preserve that one, then the rest don't matter. I think they all
matter.

And then the more distally you go, collateral supply from internal
lilacs, median sacral, all those contribute to a collateral circulation
that should be seen in some ways all connected. And that is why, more
recently in endovascular approaches, staging repair is really useful
because you can allow the surviving arteries then to remodel and
increase flow. It's why, during a type 2 repair, when you get the whole
aorta open, it's very important to block the intercostals early---either
by sewing them off or putting a little Pruitt balloon in and to stop
losing blood from that collateral supply. It keeps the pressure in the
spinal cord. Also that's why, the differential position of that blood
supply is why patients then get a particular form of problem with motor
problems and sometimes preservation of sensation.

**So purely for exam purposes and a bit of physiology. Can you remind us
how to calculate the spinal cord perfusion?**

All that is really is map minus the CSF pressure. So it's your mean
arterial pressure, take out the CSF pressure and that's what you've got
perfusing the spinal cord. It is a useful equation to remember because
it allows you to decide what's the way to enhance spinal perfusion as
much as possible, and that is to increase MAP and decrease your CSF
pressure. We do that by enhancing the mean arterial pressure as much as
possible, and draining off CSF with a spinal drain to reduce your CSF
pressure and allow more blood into the cord.

I think people perhaps get a bit hung up on spinal drainage and it's
importance. It is just as important to maintain oxygenation and
hemoglobin over a hundred, reduce blood loss and all those other things
are as crucial. Spinal drainage is an adjunct, but it shouldn't be seen
in isolation. It's one of many adjuncts to try and help prevent spinal
ischemia.

**So in regards to the mechanism for spinal cord ischemia during open
thoracoabdominal aneurysm repair, do you think it's related the blood
loss, clamp time or or implantation of the intercostals?**

I think it's multifactorial. So I think the majority is due to ischemia
scheme in terms of a watershed situation. Segments of a cord just not
getting enough blood. And the very reason the more typical area around
T7, 8, 9, to 10, is because it is in the middle between the vertebral
and internal iliac artery supply. This is probably a kin to a splenic
flexure of the colon, it's between two territories.

However, there is also potentially problems with microemboli or trashing
of a spinal arteries, which can occur in some patients. It's a slightly
confusing situation, but I think in terms of intraoperatively, blood
loss, dumps in blood pressure, with hypotensive episodes really don't
help. When do you remiplant? Again, that is a bit confusing. Some people
would argue if there's massive back bleeding, you don't need to be
reimplant because they're getting collateral supply from somewhere.

I think it will depend on how the case is going. We do use motor evoked
potentials (MEPs) but that's quite a specialist situation and you're
very reliant on the readings you get. They can be confused by leg
ischemia, cooling down or edema. But if you have already got the legs
back in circuits and got the MAP up and things weren't improving and
there was a sizable intercostals that could be reimplanted, well, then
that's worth doing. And that's why the technique of using Pruitt balloon
occlusion methods in pairs rather than ligating is good because you can
then just reimplant those. If you don't need to implant them, you can
just ligate and remove them. Whereas if you've already ligated them,
you've got a problem because you've already destroyed the ostia. We tend
to leave a branch already attached in the mid thoracic aorta to save an
anastomosis. You can, if you've got really good intercostals, fillet the
branch to open it up and sew it on like a long patch longitudinally
along the paired intercostals and then plumb it back on the other end so
it's a circuit in series with your main aortic graft. That probably
decreases the resistance to flow and that might remain patent for a bit
longer, rather than having a big 10mm graft going into a single pair of
intercostals with what are likely to have quite a high resistance, and
they probably don't last as long.

Severe spinal protocols have been described to reduce risk of spinal
ischemia or mitigate the impact of spinal ischemia in patients who
develop weakness.[@estrera2009; @yanase2012] An easy way to remember the
important components are COPS:

-   C - Cerebral spine drain status - keep for 7 days, pressure less
    than 5

-   O - Oxygen delivery - supplemental oxygen, increase hgb, increase
    cardiac index

-   PS - Patient Status - Keep BP greater than a MAP of 90mmHg

**So do you think we're good at predicting preoperatively who may get
spinal cord ischemia? You mentioned a few risk factors already that can
predict who will or won't post-operatively.**

I think we're utterly hopeless at it actually. I really don't think that
there's a good method. You can see people having an infrarenal repair
getting paralysis and you can completely replace the whole aorta from
the arch down to the iliacs with prosthetic and have people walking
around without a problem at all. So I don't really understand it and I
think that comes into the business about whether it is about emboli,
flow, or collaterals. I think it's a combination of things. When people
started embolizing intercostals preoperatively prior to endo repairs,
people thought this is a man thing---you want to keep them perfused
surely. But I think it does show the importance of maximizing the
collateral supply, and I think some people have a better collateral
supply than others. And of course, what we don't know is when you get
down to the more microscopic level of actual arterial supply at cord
level, what that is like in an inidividual patient. You can't see on
imaging. If that is already compromised, I suspect those patients are
more at risk than whether they have a macro vascular problem when things
go wrong terms of hypotension or blood loss.

Many reports state that the highest risk factor for spinal cord ischemia
includes length of aortic coverage or repair, followed by whether they
have had a prior repair, preop hemoglobin, and intraoperative
hypotension.[@bisdas2015]

**We haven't really touched on complex endovascular repairs yet, but can
you explain when you might choose a hybrid approach to this
thoracoabdominal aneurysm repair?**

So visceral hybrid operation came in really as a bridge between open
surgery and endovascular. This is a bit dated now, because it is before
custom devices and we only had thoracic stents at this time, the era of
the Talent stent, which was a very early thoracic device made by
Medtronic. Perhaps not the perfect name because it wasn't a particularly
talented, it was a difficult thing to deploy, but it actually got us
into the thoracic aorta. What we realized was that if you could operate
in one cavity, such as the abdomen, but still excluding any aneurysm in
the chest without cross camping and without rendering that patient
ischemic over a large part of their body---they could withstand that hit
much better than open cavity surgery with cross clamp and massive
reperfusion.

So the concept of a visceral hybrid was to do an extra-anatomical bypass
of the celiac, SMA and both renals from either the distal aorta or the
iliac vessels. So patients would only get sequential ischemia of one
organ at a time, say the right kidney or the celiac territory, and
during that 10 minute anastomosis, the remainder of the body and organs
were refused. And finally, at the end that, you could then put in a
thoracic device as a freebie, because you'd already perfused the organs
from distally. You'd ligated those target vessels and then you would
just excluding the aneurysm so that you were transferring blood from
above the repair to below the repair and retrogradely perfusing the
vital organs.

So it was very attractive and we started doing it quite early at St.
Mary's and initially we had some very good results in the first 30 or so
patients. And as always, then it allowed you to consider older, sicker
patients but it wasn't easy surgery. And actually I think because it was
doable in terms of just an abdominal approach and relatively familiar
territory for anyone who's done occlusive disease for the viscerals or
renals, I think a number of centers started doing small numbers and not
getting so good results. And then when better, custom made devices came
in, I think it's purpose became less and less because why would you do
that if you had an opportunity to do something which was even less
invasive.

So what we've been left with now to consider a hybrid type approach
effectively are those patients who are physiologically not fit enough
for an open approach and those patients who are anatomically not
suitable for a total endovascular approach. In some ways, they are the
worst of both worlds in that outcome group. And so I don't think you'll
ever be able to compare outcomes legitimately with the fitter group
having a fully open approach and the anatomically suitable patients
having a total endovascular.

But I must say we still see quite a lot in our multidisciplinary reviews
coming back. What surprises me is the durability of those grafts. The
visceral grafts remain patent for many years, some of them are 15 years
now. Occasionally there will be an accessory or small diseased renal
artery, and the renal grart will go down, but the others have been
extremely durable. And even though we've had to re-line the stenting
portion or extend it, the grafts have maintained really well.

A unique situation that uses a similar technique is with mycotic
aneurysms of the visceral segment of the aorta. The mainstay of
treatment is a debranching of the aorta and debridement of the infected
aorta with in situ revascularization or ax fem-fem bypass. There is an
evolving role for FEVAR, such as with most aneurysmal
disease.[@sörelius2016; @sule2016]

S**o moving on to Type IV thoracoabdominal aneurysm repair. These can be
repaired using endovascular or open techniques. Can you talk us through
your approach to open Type IV repair in terms of exposure and any tips
such as how to minimize the visceral ischemia?**

So I think an open Type IV from a subcostal approach is a doable and
durable procedure. And what I mean by that is that the hit to the
patient is not enormous, and a reasonably fit patient can get through
that reasonably well. You have to be a little bit selective, but not
super selective. For example, in my first hundred, I had one 30 day
death and one in hospital death, which was someone at about three months
who just didn't get better, so that puts it into perspective that
actually it's an operation with a very good outcome, if you get it right
at the beginning.

The approach I mentioned earlier, nothing too special. This is a supine
patient. Getting the break on the table in the right position to allow
you to extend the abdomen. You lower both ends of a table to open up
that segment of the abdomen and get better exposure. I tend to do the
vast majority via a subcostal approach, some people would call it
rooftop, then extending on the left side down below the costal margin a
bit. And it gives you really good exposure even if you have to go down
to the iliacs. It does cause a bit more of a problem getting to the
right iliac bifurcation. The left is easy, because it's right there next
to you. So that's an added complication.

The visceral rotation needs to be done carefully because what you do not
want is to create blood loss right at beginning. And as I mentioned
earlier, it's getting under the left colon along the white line onto
psoas and then getting up under psoas and I always tell the registrars
when they're doing it, you've got to go as far as possible on psoas from
below. And when you think you've gone as far as possible, you've got to
go another five centimeters. So you get right up to the diaphragm from
below. And then you can get into the supra-colic compartment around the
splenic flexure and get your fingers either side of the lienorenal
ligament and take that off the lateral and the posterior abdominal wall.
The more and more you do, the more you are freeing and the whole of the
viscera comes up towards the right side of a patient and eventually they
will rotate up and you've exposed the whole left wall of the aorta.

The first thing I then do is ensure that I've got a clamp zone, and I do
that by dividing the crus which sometimes can be really tense at that
level. The crus can act as an extrinsic wrap around the dilated aorta,
to an extent that the distal end of the crus is almost ligamentous,
causing a tight band on the aorta. I tend to get my finger underneath
that before it with a diathermy and opening it, and then very carefully
choosing the clamp zone and getting my fingers right round that area, so
I know I've got a healthy clamp zone.

The next thing I then do is look for the left renal artery. I've already
tended to make a decision about what I'm going to do with the left renal
artery, which depends on the number of things. So it depends on, to some
extent, the age of a patient, where the left renal is in terms of a
clock face. So if you're looking at an axial cut to the CT, the more the
loft renal is around before three o'clock, up to two o'clock, the easier
it is to incorporate because you've got less aortic tissue there. Once
you're beyond 3:30, round to four o'clock, it's quite a long way away
and it's quite posterior on the sidewall of the aorta, or if the left
renal i smore distal compared to the right renal. What that means is
then it's a long way away from the right renal artery, which means
you're going be leaving a larger patch of aorta. This is usually bad
news, unless you have a more elderly patient.

You're making this decision about whether you're going to try and
incorporate the left renal artery into a big big patch or whether you're
going to reimplant it separately or perform a jump graft. So you've
already thought about that, but it's crucial to find the left renal
because when you've clamped and you've done your left aortotomy, you've
got to get that aortotomy underneath and posterior to the left renal
artery so that the orifice goes up with that segment of the aorta.

Then I tend to get the iliacs out. The left is easy, it's there. I have
no qualms on the right by going back over through the peritoneum to find
the right iliac artery to expose that. I don't go around any of them. I
just find a very discrete camp zone. You don't need much, just literally
enought to put a clamp on.

And then I tend to take the fat and lymphatic tissue off the left side
of aorta. So when you open the aorta, you've not got a lot of immediate
bleeding. If you've got a retro-aortic left renal vein, you've got a
line gate that cause otherwise you'd be going through it. And
surprisingly, on CT, the main left renal vein is anterior, but there is
often a vein there which has stretched across, either a lumbar or
phrenic vein, which you should deal with prior to your aortotomy.

It's about getting everything set up before you cross clamp, because
once you cross clamp, the clock is on. So it's getting the whole team
ready for that moment and making your anatomy as perfect as possible
before you do that. Obviously it goes without saying that you have cell
salvage and we use a Belmont with the big bucket on the top of it, so
that you can rapidly give blood back when you need it.

**Can you talk a little bit more about a Carrel patch and when would you
choose to do a jump graft to the left renal rather than encompass all
the vessel vessels onto that patch?**

I tend to think of a Carrel patch more in a way with a type 3 repair,
because with a type 3 repair, you've done your proximal anastomosis and
then what you're doing is you're putting on a patch of aorta to include
the celiac, SMA, and right renal, which tend to be together, whereas
sometimes the left renal is a bit away. The more tissue you leave there,
the more chance that aortic tissue will dilate to over time, hence the
patch aneurysm. If your patient has got some form of connective tissue
disease, we tend to reimplant directly.[@derango2011; @afifi2017] There
is a very nice graft available with four side bunches already put on and
you can go straight onto the ostia. So you're basically leaving no
aortic tissue at all.

For type four, you are doing an oblique anastomosis and you have to be
aware that the right side of the aorta is really left there. It's a
compromise, these patients with atherosclerotic type aneurysms, they may
be in their sixties, seventies or even into their eighties. Even the
good candidates, they're not going to live 25-30 years, and therefore
over time that segment may begin to dilate a bit. I think that is
acceptable. Half of that segment is Dacron and the other bit may dilate.

I think if you've got a Carrel patch, which really balloons out, that's
something which is different. We don't have good dates as to when those
will give away and rupture. I think what is clear is that if you've got
dehiscence between your suture line and your graft, that is a dangerous
situation, akin to a false aneurysm. And although it may look similar on
CT, that's a different beast and they're at risk at any stage. True
aneurysmal dilation of a segment that is left behind is a bit different
and I think that's a bit safer. In essence, what you're trying to do is
a compromise between leaving as little aortic tissue as possible, but
also getting the patient alive through their first repair safely.

If I know I'm not going to incorporate a left renal, then I will sew on
a six or eight millimeter side branch onto the tube golf before I cross
clamp, because that saves you one anastomosis. And then now my favorite
technique is just to amputate the left renal artery and sew that
directly onto your branch and leave that in a bit of a lazy C
configuration in the paracolic gutter, so as the rotation comes back,
it's not under tension. The other technique is to have very short graft,
right from your aortic prosthetic, but you've got to really judge how
that will sit when the kidney is back in its anatomic position. So it
can't come off the anterior aspect of the tube graft. It needs to be
further down and that's awkward to judge and I think we're probably not
good at that so the lazy C is a better approach.

I much prefer that to trying to either reimplant the native artery
directly onto the Dacron, as they tend to restenose or try to bring the
aortic sidewall down on to the Dacron. I think that's fraught with
difficulty. You've often got calcification at the ostium, and it's also
very difficult because you've got the rest of your anastomosis really
close and sometimes not enough room to bring your clamp down, which is
exactly what you want to do. The left kidney will take a bit of an extra
ischemic hit, but you want to be perfuse the right renal and viscera.
You've got to have to bring your camp down below your proximal
anastomosis.

When it comes to late complications from TAAA repair, 8% are from
progression of aortic disease and 3% are related to the graft repair.
Risk factors associated with late events include female sex, partial
aneurysm resection, expansion of remaining native aorta or initial
aneurysm rupture.[@clouse2003]

**Have you ever had to treat the Carrel patch aneurysm in your career?**

We have a number from previous Type 3 repairs and I think these are very
suitable for fenestrated or branched devices. You've got a beautiful
lending zone, proximally and distally. Why not? These tend to be
well-suited to that and it's a much easier approach mixing endo and
open, changing from one to the other, I think that's fine. It's just at
a different stage of a patient's life and repair

**Any final summary or closing words about aortic surgery?**

We have a bit of a tipping point with open aortic surgery at the moment,
certainly in the UK. Looking at registry data, many are tipping back to
open now. Whether that was as a result of NICE guidelines, I suspect
not, perhaps that just put it more into focus. I think many people are
seeing more problems with patients surviving after what was very good
endovascular surgery at the time, but they've outlived the repair. Now
we've got problems with patients where you got to wonder whether that
wasn't perfect anatomy and should they have had open surgery?

Now the difficulty we've got at the moment is the patients that perhaps
weren't that suited for endovascular repair, did well initially from it
and they are paying the price later on. But those very patients are the
ones that are also more difficult from an open approach. They are
patients with shorter, more tortuous necks or more calcification. There
is a concern that there is an era of surgeons now that haven't done as
much open aortic surgery, who may not be as confident with adverse
anatomy.

That lack of confidence influences your decision-making, so patients
don't get a full appraisal of what options are available. The default
then may be to go with a less than perfect and endovascular option. I
agree, this may be less easy to kill a patient upfront with an endo
option but you perhaps pay for that later on. This is a very difficult
thing to get around and we've got to get to a compromise of finding the
patients with the likely better life expectancy and sending them to
groups with a larger open practice and get them through a big operation
safely and capitalize on those benefits.

The really lucky ones are the ones that are anatomically really suited
for endovascular repair and their sack really shrinks and their seal
zones remain good. They are the best of both worlds as they tend to also
be fitter with less extensive disease and get the benefits from a less
invasive approach. Not all patients are the same and we've got to now
accept that we've gone down the line of working with industry, which
they didn't necessarily focus on durability. What they wanted to do is
to extend the applicability, to treat more patients and get better,
lower profile devices to go for these percutaneous cardiology market in
the United States. And we're now paying the price of some of those
decisions, so we've got to reboot and take a stance on which patients
are going to actually benefit from which approach and have a better
evaluation of that going forward.

## Additional Resources

-   [Yale Vascular Review Podcast Episode 1: Thoracoabdominal
    Aneurysms](https://podcasts.apple.com/us/podcast/yale-vascular-review/id1587352652)