## Thoracic Outlet

Author: *Nedal Katib*

```{r echo=FALSE}
library(embedr)

embed_audio("https://traffic.libsyn.com/audiblebleeding/VSITE_TOS_02auph.mp3")

```

Thoracic Outlet Syndrome = A constellation of signs and symptoms relating to the compression of the neurovascular structures that occurs as these structures travel between the thoracic aperture and the upper limb.

Types: Neurogenic, Venous and Arterial

-   vTOS -- 2-3%

-   aTOS -- 1%

-   nTOS -- \>95% [@humphries124ThoracicOutlet2019]

### Anatomy

Understanding the anatomy of what is collectively referred to as the thoracic outlet is the best way to thoroughly appreciate this topic.

Anatomy from anterior to posterior

-   Subclavian vein

-   Phrenic nerve

-   Anterior scalene muscle attachment to the first rib

-   The subclavian artery

-   The brachial plexus

-   The middle scalene muscle.

Three spaces where the neurovascular structures are at risk of compression:

1.  Interscalene Triangle

2.  Costoclavicular Passage[@garygwindAnatomicExposuresVascular2013]

3.  Subcoracoid Space[@garygwindAnatomicExposuresVascular2013]

**Interscalene Triangle:**

Appreciating the attachments of the Anterior and Middle Scalene Muscles on the first rib becomes important in the diagnosis of the various types and also the ultimate surgical management of the compression.

**Anterior Scalene:**

Attachments: Anterior Tubercles of the four 'typical' cervical vertebrae (3-6) AND the scalene tubercle on the upper surface of the first rib.

-   Phrenic nerve runs along anterior scalene muscle and injury can cause ipsilateral diaphragm paralysis.

**Middle Scalene:**

Attachments: The posterior tubercles and intertubercular lamellae of all the cervical vertebrae AND the Quadrangular area between the neck and subclavian groove of the first rib. [@mcminnLastAnatomyRegional2019]

-   Long thoracic nerve runs along middle scalene muscle and injury can cause winged scapula.

**The First Rib:**

-   The broadest and flattest of the ribs and is an 'Atypical Rib'.

-   The upper surface of the first rib has the scalene and quadrangular tubercles for attachments of the anterior and middle scalene muscles respectively. There are also three grooves for the Subclavian Vein, artery and the Lower Trunk of the Brachial Plexus.

-   The Inferior Surface is smooth and inferior and medially has an attachment for the suprapleural membrane, Sibson's fascia AKA scalenus minimus, which is tethered to the C7 vertebrae.

-   This is the passage of the subclavian vein largely as it emerges through the tight space created by the clavicle, the subclavius muscle and the costoclavicular ligament and also more posteriorly this can also compress the artery and nerves as the space can also be narrow in relation with the scapula and subscapularis. [@garygwindAnatomicExposuresVascular2013]

**Subclavius Muscle:**

-   Attached to the costochondral junction of the first rib and is inserted into the subclavian groove on the inferior surface of the clavicle. [@mcminnLastAnatomyRegional2019]

-   This space is best appreciated by intimate knowledge of three things:

    -   The Coracoid Process and its attachments

    -   The Pectoralis Minor Muscle

    -   The Clavipectoral Fascia

**The Coracoid Process:**

-   Arising from the Scapula as a 'process', this broad-based bony landmark offers attachment to muscles and ligaments.

-   The relevant attachments being the pectoralis minor muscle occupying the medial border for about 2cm behind its tip. The tip itself having a medial and lateral facet for the short head of biceps and the coracobrachialis muscles respectively.

**Pectoralis Minor Muscle:**

Attached to the bone of the third, fourth and fifth ribs AND the medial border of the coracoid process.

**Clavipectoral Fascia:**

A sheet of fascial membrane that fills the space between the clavicle and pectoralis minor splitting and encompassing the subclavius muscle. Its superior portion is what can be thickened and become a tight band referred to as the costocoracoid ligament.

**Phrenic Nerve Anomaly:**

The Phrenic Nerve normally runs anterior to the Subclavian Vein. A rare anomaly is the nerve compressing the vein anteriorly and in very rare circumstances due to the timing of development can run through the vein itself.

Anomalous anatomy can also cause TOS especially when patients have a Cervical Rib and anomalous first ribs or a congenital band attaching to the first rib.

-   Incidence of anomalous first ribs and cervical ribs is 0.76% and 0.75% respectively.

-   Incidence of bands are as high as 63% in the general population. [@humphries124ThoracicOutlet2019]

nTOS

-   Scalene Triangle compression -- most common cause of brachial plexus and neurogenic TOS

-   Cervical Rib and Anomalous First Rib

aTOS

-   Cervical Rib and Anomalous First Rib

-   Scalene Triangle compression

vTOS

-   Costoclavicular Passage

-   Subcoracoid Space

### Presentation

-   Identify symptoms and thoroughly interrogate timing

-   Exclude history of trauma

-   Associated symptoms like headache, visual disturbance, neurology in the upper limb

-   Exclude Carpal Tunnel and Antecubital Tunnel Syndromes if symptoms are isolated to the arm or forearm or hand

-   Patients with vTOS may present acutely and have acute or sub acute Upper Limb DVT

-   Patients with aTOS need to be investigated and assessed urgently given risk of ischemia.

### Evaluation

#### Clinical Examination

Provocative maneuvers are largely used for nTOS. While these are described and mentioned in most texts their utility largely is beyond the scope of a vascular surgeon's assessment and diagnosis of nTOS.

**Adson Test**

-   Extended abducted and externally rotated arm -- palpate radial pulse

-   Rotate and laterally flex the neck to the ipsilateral side while inhaling deeply.

-   A positive test results in reduction or complete obliteration of radial pulse

**Roos Test / EAST test**

-   Patient seated and both arms abducted 90 degrees and externally rotated and elbows flexed at 90 degrees.

-   Open and close hands for 3 minutes or until pain or paraesthesia sets in.

**Elveys Test**

-   Abduct both arms to 90 degrees with elbows extended and dorsiflex both wrists.

-   If pain is elicited as wrists dorsiflexed then test is positive.

-   A further manoeuvre is then performed, laterally flex the head on each side, if pain is elicited on the contralateral side to which the head is flexed then test is positive. [@humphries124ThoracicOutlet2019]

#### Non-invasive imaging or vascular lab studies

-   DBI

-   Arterial Duplex

-   Venous Duplex

-   CT -- CTV commonly performed in acute upper limb DVT and suspicion of vTOS

-   CTA for the evaluation of aTOS and excluding other causes of embolisation

-   MRI -- for further evaluation of the anatomy and related neurovascular compression

-   Electromyography and Nerve Conduction Studies for nTOS

### Management

After the appropriate evaluation, if decompression of thoracic outlet is deemed appropriate, there are multiple approaches to the first rib resections.

**Transaxillary**

-   *Advantages:* Cosmetically more appealing as it has a limited hidden scar

-   *Disadvantages:*

    -   Difficult to visualize the anatomy, dependent on good assistance

    -   Risk of injury to T1 nerve root, phrenic nerve, long thoracic, brachial plexus , subclavian vein and arterial with limited exposure to repair

    -   Not able to approach cervical ribs, scalene triangle or patch vein.

**Supraclavicular**

-   *Advantages*

    -   Good for scalene triangle access and debulking and cervical rib resection

    -   Required for aTOS if arterial reconstruction necessary

-   *Disadvantages*

    -   Unable to decompress venous compression or visualize vein adequately

    -   Cosmetically less appealing

**Infraclavicular**[@siracuseInfraclavicularFirstRib2015]

-   *Advantages*

    -   Good access for venous decompression

    -   Allows for excision of subclavius muscle and costoclavicular ligament

-   *Disadvantages*

    -   Unable to expose subclavian artery or decompress brachial plexus.

    -   Difficult to access most posterior aspect of rib

    -   Cosmetically less appealing

**Paraclavicular**

-   *Advantages*

    -   Useful if mixed etiology TOS to adequately decompression all neurovascular structures

-   *Disadvantages*

    -   Requires two incisions one above and below the clavicle

#### Post operative complications

-   Post operative patients with hemodynamic instability and ipsilateral effusion on xray should go back to OR for exploration and hemorrhage control. [@rinehardtCurrentPracticeThoracic2017]

-   Chyle leak often managed with adequate drainage and medium chain fatty acid diet. Persistent leak should undergo wound exploration and ligation of thoracic duct (most often encountered on the left) or VATS thoracic duct ligation.[@delaney2017] IR embolization has also been shown to be effective.[@cope1999]

### vTOS

#### Demographics

-   Incidence: 2/100,000 persons

-   Age: 18 years to 30 years [@illigComprehensiveReviewPagetSchroetter2010]

-   M\>F

-   **Paget Schroetter Syndrome**

    -   First defined by Hughes in 1949 in reference to Sir James Paget who in a hundred years earlier defined acute arm swelling and pain as possibly related to vasospasm and then von Schroetter who in 1884 attributed to the presentation to subclavian and axillary vein thrombosis. [@humphries123ThoracicOutlet2019]

    -   Now vTOS and Paget Schroetter Syndrome are used synonymously.

    -   Paget Schroetter Syndrome accounts for 10-20% of all upper extremity deep vein thrombosis. [@sekharYearbookVascularEndovascular2018]

#### Presentation

-   Upper Limb edema, pain and cyanosis. Edema affects the shoulder, arm and hand and characteristically non pitting.

-   Collateral vein dilatation over the shoulder, neck and anterior chest wall to accommodate for the increased venous hypertension. [@humphries123ThoracicOutlet2019]

-   Pain on exertion of the upper limb described as stabbing, aching or tightness.

-   The reported incidence of PE following Upper Limb DVT is \<12%. [@humphries123ThoracicOutlet2019]

#### Evaluation

Upper extremity venogram is a very useful modality for diagnosis. Compression likely will not be seen in normal orientation, however can be demonstrated with provocative maneuvers including 90 degree arm abduction and external rotation.[@moriarty2015]

-   A differential diagnosis for Upper Limb DVT

    -   vTOS

    -   Congenital Phrenic Nerve anomaly

    -   History of fracture, clavicular fracture and malunion

    -   Repetitive arm provocative maneuvers, check occupation and history of body-building

        -   Pectoralis Minor Hypertrophy.

-   Exclude Pulmonary Embolism

-   Exclude Venous Gangrene and Phlegmasia of the upper limb

#### Management

Limited evidence due to lack of RCT's. Majority of evidence based on retrospective studies.

-   Prevent immediate risk

-   Return patient to unrestricted use of the affected extremity

-   Prevent recurrence of thrombosis without the need of long-term anticoagulation

-   Prevent long term Post Phlebitic Limb Syndrome

##### Medical Management

-   As per ACCP Guidelines: Initial management is anticoagulation regardless of etiology. [@kearonAntithromboticTherapyVTE2016]

    -   The limitations of anticoagulation alone are that the slow recanalization of the thrombus may lead to eventual valvular damage and intravenous scarring. [@sekharYearbookVascularEndovascular2018]

    -   Thrombolysis has been considered superior to anticoagulation alone in minimizing valvular damage due to residual clot. [@urschelSurgeryRemainsMost2008]

    -   Systemic Lysis -- non favored due to risk of intracranial hemorrhage. [@grunwaldCatheterDirectedThrombolysisTreatment2004]

    -   Catheter Directed Lysis (CDT) -- carries a lower risk of intracranial hemorrhage.

    -   Patient should be maintained in a compression sleeve until definitive decompression can be performed.

-   Optimal timing of CDT

    -   Within 14 days of onset of thrombosis. Excellent results have been reported following CDT if initiated before 14 days. [@wilsonFibrinolyticTherapyIdiopathic1990]

##### Surgery

-   After initial management patients are generally divided into two groups, unsuccessful or successful thrombolysis.

-   Persistent stenosis or signs of extrinsic compression, on venography, has generally been perceived as a significant risk of recurrent thrombosis.

-   Surgery for vTOS remains to be mainly Rib Resection and decompression of the subclavian vein with or without venolysis and patch plasty either surgical or endovenous.

-   Surgical treatment of severe resistant subclavian vein stenosis in the setting of vTOS is rib resection by paraclavicular approach and vein patch plasty. [@melbyComprehensiveSurgicalManagement2008]

-   Venous occlusion in vTOS may be treated with jugular turn down or venous bypass to IJ of SVC if patients remain symptomatic. [@vemuriDiagnosisTreatmentEffortinduced2016]

#### Summary

##### Controversy

-   There is a lack of consensus around the necessity of surgical rib resection, the timing and the requirement for vein patch plasty.

-   Options post recanalization:

    -   Deferring surgical decompression for 1-3 months after thrombolysis to allow for healing of the venous endothelium and resolution of the acute inflammatory process. [@humphries123ThoracicOutlet2019]

    -   Decompression during the same admission, as the thrombolysis, with the main benefit being to reduce the risk of re-occlusion. [@humphries123ThoracicOutlet2019; @molinaPagetSchroetterSyndromeTreated2007]

    -   Post decompression venography and treatment 2 weeks post rib resection may help to prevent recurrence and long term vein patency. [@changRoutineVenographyFollowing2012]

##### Landmark papers

1.  Lugo J et al -- Acute Paget Schroetter syndrome: does the first rib routinely need to be removed after thrombolysis? Annals of Vascular Surgery 2015 [@lugoAcutePagetSchroetter2015]

    1.  Systematic literature review analysis. Patients divided into three groups

        1.  First Rib resection (FRR) -- n=448

        2.  First Rib resection and endovenous venoplasty (FRR and PLASTY) n=68

        3.  No further intervention after Thrombolysis n=168

    2.  Symptom relief after initial follow up more likely in FRR (95%) and FRR and PLASTY (93%) compared to no rib removed (54%) -- p\<0.0001

    3.  Results showed superior patency with FRR and PLASTY and FRR compared to anticoagulation alone.

    4.  Conclusion was that patients are more likely to experience greater long-term results with FRR compared to no FRR.

2.  Sajid MS et al -- Upper limb vein thrombosis: a literature review to streamline the protocol for management. Acta Haematology 2007 [@sajidUpperLimbDeep2007]

    -   Comprehensive review identifying the key papers on this topic and allows for a clear view of the best management strategy.

3.  Vemuri, C., Salehi, P., Benarroch-Gampel, J., McLaughlin, L. N., & Thompson, R. W. (2016). Diagnosis and treatment of effort-induced thrombosis of the axillary subclavian vein due to venous thoracic outlet syndrome. *Journal of Vascular Surgery: Venous and Lymphatic Disorders*, *4*(4), 485--500. [@vemuriDiagnosisTreatmentEffortinduced2016]

    -   Comprehensive summary of management strategy for effort induced thrombosis.

### aTOS

#### Presentation

-   Most common: Hand ischemia due to arterial compression or microembolization with subclavian artery aneurysm and pulsatile supraclavicular mass [@boll122ThoracicOutlet2019]

-   Less common: Exertional pain, unilateral Raynaud's Phenomena, retrograde embolisation and neurological symptoms

-   Differential Diagnosis

    -   Trauma

    -   Primary and Secondary Raynaud's Phenomena

    -   Small Vessel Vasculitis

    -   Connective Tissue Disorders

    -   Thromboangiitis Obliterans

    -   Arterial Embolisation -- Aortic or Central Source

    -   Radiation Arteritis

    -   Atherosclerotic / Dissection causes

-   The different anatomical abnormalities causing aTOS [@boll122ThoracicOutlet2019]

    -   Cervical Rib (60%)

    -   Anomalous First Rib (18%)

    -   Fibrocartilaginous band (15%)

    -   Clavicular Fracture (6%)

    -   Enlarged C7 transverse process (1%)

#### Evaluation

Clinical Examination

-   Audible Bruit / Palpable thrill over the supraclavicular fossa

-   Pulsatile mass

-   Distal ischemic lesions in the distal hand -- Splinter hemorrhages

-   Positive Adson Test

Most useful studies are pulse volume recordings (PVR) and duplex to identify aneurysm or sites of embolization. Stress test is not reliable for diagnosis. [@vemuriClinicalPresentationManagement2017; @criadoSpectrumArterialCompression2010]

#### Management

-   Symptomatic patients are generally indicated for treatment. Unlike asymptomatic patients in whom it may be appropriate to manage conservatively. [@boll122ThoracicOutlet2019]

    -   Scher Staging of aTOS

        -   Stage 0: Asymptomatic

        -   Stage 1: Stenosis of Subclavian Artery with minor post stenotic dilatation with no intimal disruption

        -   Stage 2: Subclavian artery aneurysm with intimal damage and mural thrombus

        -   Stage 3: Distal embolisation from subclavian artery disease

-   Supraclavicular rib resection is the most suitable for adequate arterial reconstruction. Transaxillary has been argued to offer more complete rib resection however arterial repair is not possible in this approach.

-   Subclavian artery repair is necessary in Scher Stages 2 and 3 and in some cases 1. Arterial repair with conduit either GSV, Femoral Vein or prosthetic have been described. Ringed PTFE offers good patency and resistance to kinking in this functional anatomical location.

### nTOS

#### Demographics

Neurogenic TOS is largely a clinical diagnosis with symptoms and signs pertaining to nerve compression most commonly the lower trunk of the brachial plexus.

-   F\>M -- 70% Female

-   Ages 20-40

-   Occupational Exposure

-   Trauma history - often associated with recent history of neck trauma.

#### Presentation

-   Symptoms [@sadeghi-azandaryaniThoracicOutletSyndrome2009; @sandersDiagnosisThoracicOutlet2007]

    -   Paraesthesia (98%)

    -   Trapezius pain (92%)

    -   Neck, shoulder or arm pain (88%) - usually involves nerve roots so isolated hand symptoms is rare.

    -   Supraclavicular pain with or without occipital headache (76%)

    -   Chest pain (72%)

    -   Weakness

    -   Swelling

-   Positional Effects

    -   Reproducible exacerbation of symptoms

    -   Lying supine with arms overhead

    -   Overhead activities -occupational or recreational

-   Weakness and Muscle Atrophy

    -   Hypothenar atrophy

    -   Drop-off in athletic performance

    -   Inability to carry out activities of daily living

#### Management

As the patient has already seen multiple specialists and physiotherapists, the role of the vascular surgeon with nTOS is often limited but should focus on:

-   Exclude other causes

-   Confirm diagnosis -- Neurophysiologic Tests (EMG and NCS)

-   Seek alternate opinion

-   Trial of Physiotherapy and non-operative management - patients should be evaluated and undergo a 6 week course of physical therapy. This physical therapy focuses on scalene and pectoralis stretching improving mobility of the shoulder and strengthening the arm. Many improve with physical therapy. [@baldermanPhysicalTherapyManagement2019]

-   Anterior scalene lidocaine block may provide temporary symptom relief (\~7 days) and may help identify those patients most likely to benefit from surgical decompression. [@salhanPC214UltrasoundGuidedAnesthetic2016; @lumImpactAnteriorScalene2012]

-   Botulinum injection may give an average of 6 weeks of relief. [@salhanPC214UltrasoundGuidedAnesthetic2016]

-   Be selective in patients who may require surgery

Surgery with Rib resection often is accomplished with transaxillary or supraclavicular approach, particularly if scalenectomy or cervical rib resection is necessary.
