# Trauma - Peripheral {#sec-trauma-peripheral}

Authors: *Kevin Kniery, Nakia Sarad, and Todd Rasmussen*

```{r echo=FALSE}

library(embedr)

embed_audio("https://traffic.libsyn.com/audiblebleeding/Rasmussen_Final_Final.mp3")

```

## General Principles

**DO NOT GET DISTRACTED**

-   These patients are often poly-trauma patients with likely other injuries

-   Follow ABCDE of the primary survey

    -   Identify bleed and hold pressure to stop the bleeding

    -   Pressure can be manual pressure, such as placing a finger in the wound, or applying a tourniquet

    -   Once bleeding is effectively controlled, RESUSCITATE and continue the primary survey to address other life threatening injuries

### Epidemiology

Penetrating extremity trauma is leading cause of peripheral vascular injuries (75-80%)

Most common arterial injury found in femoral or popliteal arteries (50-60%), then brachial artery (30%)

### Types of Injuries

Can occur with either blunt or penetrating trauma

1.  Complete Wall Defect (hemorrhage or pseudoaneurysm)
2.  Intimal Injury (subintimal/intramural hematomas, flaps, disruptions)
3.  Arteriovenous fistulas
4.  Complete Transection (with hemorrhage or occlusion)
5.  Spasm

### Presentation

**Hard Signs of Peripheral Vascular Injury**

-   Active Hemorrhage

    -   Obvious bleeding (arterial or venous)

    -   Can be pulsatile or history of bleeding in field

-   Profound Ischemia of the extremity

    -   Determined by absence of palpable pulse or dopplerable signal beyond the area of injury

-   Expanding hematoma

    -   Can occur underneath a closed wound/injury

-   Audible Bruit or Palpable thrill near site of injury

    -   Concern for an arterial-venous fistula, often high flow

**Soft Signs of Peripheral Vascular Injury**

-   Subjective reduced or unequal pulses

    -   Diminished blood flow to extremity

    -   Weak, but audible arterial doppler signal

-   Large non-pulsatile hematoma

-   Orthopedic injury patterns carrying a high index of suspicion of vascular injury

    -   Examples - posterior knee dislocation, displaced long bone fractures

-   Penetrating wound in proximity to a major axial vessel

-   Peripheral Nerve Injuries

    -   Femoral nerve injury

        -   Paresthesia to anterior thigh

        -   Decreased hip flexion and knee extension

    -   Sciatic nerve injury

        -   Paresthesia to lateral leg and dorsal/lateral/plantar foot

        -   Weakness of foot plantar flexion

    -   Tibial nerve injury

        -   Paresthesia over heel

        -   Weakness of plantar flexion

    -   Deep peroneal nerve injury

        -   Paresthesia of first digital interspace

        -   Foot drop [@bulger2014]

### Imaging

**Continuous Wave Doppler**

-   Handheld device that can amplify arterial signal to measure quality of pulse

    -   Triphasic, biphasic, monophasic, or absent

-   Injury Extremity Index

    -   Utilizes continuous wave doppler with manual blood pressure cuff to obtain objective measurements of perfusion

    -   On injured extremity, inflate cuff proximal to arterial signal and measure pressure at which arterial signal diminishes. Compare to a normal/non-injured extremity. Injury extremity index is the ratio between these two values.

    -   If patient in shock and cold, repeat injury extremity index as the patient is resuscitated and warmed

    -   **Arterial Pulse Index \> 0.9**, no flow limiting vascular injury

        -   Recommend observation

    -   **Arterial Pulse Index \<0.9**, flow limiting vascular injury likely

        -   Recommend further imaging with CTA [@rasmussen2022]

**CT angiography (CTA)**

-   Gold standard for evaluation of extremity vascular injury

-   Ensure appropriate timing of contrast to follow-through to distal extremity

    -   Can occur in conjunction with CT imaging of head/chest/abdomen/other extremities to evaluate for traumatic injury

**Invasive angiography**

-   Has been readily replaced by CTA for evaluation of extremity vascular injury

### Management

If patient has hard sign of vascular injury, OR for exploration and vascular repair/bypass

If patient has suspicion of vascular injury (soft signs), recommend bedside injury extremity index.

If injury extremity index \> 0.9, recommend observation.

If injury extremity index \< 0.9, recommend further imaging with CTA or angiography (if patient stable). If CTA positive for occlusion or extravasation, OR for operative repair.

### Operative Approach

**Exposure Basics**

-   Prep patient widely

    -   Any lower extremity injury, prep patient from umbilicus down to both legs

    -   Anticipate need for proximal control, intraoperative angiograms at the femoral level, and potential harvesting of saphenous vein for conduit

-   Recommend leaving tourniquet on and prep into field

    -   Removing tourniquet prematurely can result in arterial bleeding, leading to hypotension, hemorrhagic shock, and multi-organ system failure

    -   Communicate with anesthesia and OR team when tourniquet will be put down and have blood ready for transfusion

-   Incision

    -   Recommend making incision twice as long as what you would initially anticipate

    -   Important to have long incision to get appropriate control and visualization of injury

-   Junctional Hemorrhages

    -   Junctional area between the torso and extremity, most difficult to control

    -   Lower extremity vessels include distal external iliac and common femoral

        -   Commonly presents as a groin hematoma

    -   Upper extremity vessels include subclavian and axillary

::: callout-tip
## Take a Look

[You can review surgical exposure of lower extremity arteries here.](https://thoracickey.com/surgical-exposure-of-the-lower-extremity-arteries/)

[You can review surgical exposure of upper extremity arteries here.](https://onlinelibrary.wiley.com/doi/epdf/10.1002/9781118481370.ch25)
:::

**Repair**

-   Gain proximal and distal control

-   Debride injury back to healthy tissue

-   Perform thrombectomy

    -   Both proximal and distal to area of injury using Fogarty catheter to completely clear the inflow/outflow thrombus

    -   Once thrombus burden removed, apply 40-60cc of regional heparinized saline down the outflow before applying the clamp. Perform again on the inflow.

-   Types

    -   Primary Repair

        -   Good for focal injuries (grazing wounds or stab wounds from a knife) where there is minimal tension and arterial lumen maintains its integrity after debridement to healthy tissue

        -   Can consider with venous injuries due to higher compliance or when vessels are redundant (ie brachial artery)

    -   Patch Repair

        -   Also good for focal injuries not amenable to primary repair

        -   Again, can perform if there is no concern for tension or compromise of arterial lumen

    -   Interposition graft

        -   Most common repair type, avoids issue of tension and compromise of arterial lumen

        -   Conduit types

            -   Autologous vein (great saphenous vein)

                -   Preferred choice with concern for contamination and for more distal extremity injuries (i.e. brachial, radial, SFA, and popliteal)

                -   Saphenous vein from contralateral extremity (non-injured) routinely recommended

                -   Ipsilateral saphenous vein CAN be used if there is no deep vein injury and it is part of the incision/exposure

            -   Prosthetic

                -   Preferred choice if vein not available or injury is more proximal (axillary, subclavian, proximal femoral, iliac)

                -   ePTFE or Dacron

    -   Ligation

        -   Dependent on location of injury and overall hemodynamic status of patient

        -   If patient unstable, ligate as damage control maneuver [@liang2016; @fox2012]

**Heparinization**

-   Recommend selective heparinization

-   If patient has isolated extremity injury, recommend systemic heparin during revascularization

-   If patient has concomitant injuries (i.e. head trauma, torso bleeding, or extensive soft tissue injury), recommend regional heparin flushed up and down injured vessel [@liang2016; @fox2012]

**Shunts**

-   Can be utilized in damage control maneuvers to prevent need for ligation and achieve temporary perfusion

-   Larger caliber vessels with high flow can be shunted without need for heparinization for 4-6 hours

-   Smaller caliber vessels (in distal extremities) usually clot off but do not cause harm when clot occurs intra-operatively as the vessel needs to be re-assessed for repair

    -   However, recommend that shunts are used in patients that do not have contraindications to systemic heparin use

-   Types

    -   Javid

    -   Sundt

    -   Argyle

        -   Has advantage of multiple sizes

    -   Pruitt-Inahara

    -   Makeshift shunts -- small caliber chest tubes

        -   Can place in injured vessel proximally and controlled with either ligature around vessel to lock shunt in place or rubber vessel loop

-   Placement

    -   Insert in injured vessel proximally first, then allow some pulsatile bleeding to allow any thrombus to exit before inserting it distally

    -   Shunts can be secured either with heavy silk tie or plastic vessel loops

    -   Can use doppler with water or acoustic gel over shunt to verify arterial flow

    -   [More information about the types and use of intravascular shunts can be found here.](https://thoracickey.com/surgical-damage-control-and-temporary-vascular-shunts/)

**Fasciotomies**

-   Avoid hesitation to perform 4-compartment fasciotomies in threatened limb ischemia

-   Recommend prophylactic fasciotomy to avoid compartment syndrome

-   Especially important when transporting patients to higher level of care facilities

-   Two-incision Four Compartment Lower Extremity Fasciotomy can reviewed here [@bowyer2015]

    -   [Reference points for lateral incision here.](https://link.springer.com/article/10.1007/s40719-014-0002-7/figures/2)

    -   [Reference points for medial incision here.](https://link.springer.com/article/10.1007/s40719-014-0002-7/figures/3)

-   [Comprehensive review of fasciotomy techniques in both upper and lower extremities can be reviewed here.](https://www.wheelessonline.com/disaster-preparedness-toolbox/4-fasciotomy/)

## Lower Extremity Arterial Injury and Management

### Iliac Vessels

**Exposure**

-   Retroperitoneal exposure preferred - oblique incision in lower quadrant of abdomen (i.e. transplant incision)

-   Midline laparotomy can also be considered

-   Groin hematomas can either be iliac or femoral etiology, recommend extensive prep with either transplant incision or midline laparotomy incision to be able to gain common iliac artery control if needed

**Repair**

-   Internal iliac injury

    -   Prefer ligation

        -   Difficult access for exposure and repair

        -   Patients usually in hemorrhagic shock and control is time-consuming and difficult to achieve

        -   Can be safely achieved, pelvic ischemia rare due to collateral blood supply from contralateral iliac vessel

    -   If repair can be performed, recommend larger needle (SH blunt tip needle on 3-0 or 4-0) for repair due to low visibility in pelvis

-   External iliac injury

    -   Repair at all costs

        -   Gain control first then decide on method of repair depending on patient stability (immediate repair or temporary repair with vascular shunt)

        -   14 French Argyle vascular shunts can be used on iliac vessels

        -   May need to use prosthetic interposition graft due to larger caliber of vessels

    -   Ligation has high morbidity and mortality, should be avoided

        -   If external iliac artery is ligated, patient will experience proximal limb ischemia and will either need an above knee amputation (AKA) or hip disarticulation

        -   In life or death situations, ligation and subsequent amputation is inevitable to save a patient's life

        -   Can consider temporary ligation with return to OR in 2-3 hours to re-establish inline flow (consider cross femoral graft) when patient is more resuscitated, however, not common in trauma situation

### Femoral Vessels

Includes the Common Femoral Artery (CFA), Superficial Femoral Artery (SFA), and the Deep Femoral (Profunda femoris)

**Exposure**

-   Proximal CFA exposure similar to exposure of external iliac (midline laparotomy or transplant incision)

-   Distal CFA, SFA, and Deep Femoral can be exposed with vertical groin incision (below inguinal ligament midway between pubis and ASIS over anterior proximal thigh) or oblique groin incision (directly beneath inguinal ligament or few centimeters distal)

**Repair**

-   Gain control

    -   May be difficult to only use vessel clamps for more proximal injuries

    -   At common femoral junction, can use Fogarty catheter into orifice of deep femoral with balloon inflated to control back bleeding

    -   If SFA injured, can clamp distal CFA for control

-   Recommend shunt placement

-   Repair with primary, patch, or interposition graft (autologous vein preferred)

-   Ligation also has high morbidity and mortality, should be avoided (see iliac section for consequences of ligation and options of shunting) [@abouali2017; @subramanian2008]

### Popliteal Artery

**Exposure**

-   Need to gain control of popliteal artery above and below knee

    -   Above knee popliteal artery is a continuation of the distal SFA through the adductor magnus (Hunter's canal)

-   Position patient in "frog-leg" with bump of rolled towels placed underneath calf

-   Make medial incision from above the knee to mid-thigh

    -   Locate the distal SFA just at or beyond Hunter's canal in order to locate the above knee popliteal artery

-   Move bump to above the knee and make a medial incision from below knee to mid calf

    -   Expose the gastrocnemius and soleus muscles and bring down to the inferior edge of the tibia to open the below the knee popliteal space

-   Retraction and good lighting is key

    -   Can use Weitlaner retractor, Pilling retractor, or Henly popliteal retractor to retract muscles and better visualize space

    -   Recommend narrow handheld retractor (appendiceal or Wylie renal vein retractor) on either the superior or inferior aspect of below or above knee incision, respectively, to gain more exposure of the popliteal space

**Repair**

-   Recommend bypass repair (autologous vein preferred if available)

    -   Inflow from distal SFA to distal below knee popliteal target

-   Always check repair with intraoperative doppler and check distal flow to foot

    -   If signal goes down and you are concerned about the technical repair, be prepared to re-open and pass thrombectomy catheters proximally and distally to evaluate issue

-   Even with good technical repair, spasm may occur

    -   Common among young patients

    -   Signal usually improves after re-warming and resuscitation

    -   Ensure that there is audible flow in the bypass and patient well resuscitated prior to re-opening injury to assess repair

    -   On-table angiogram also an option, however, spasm may appear as occlusion and repair is unnecessarily re-opened

    -   **Important to note: Water hammer signal is not appropriate audible flow as it indicates diastolic flow in the arterial signal**

### Tibial Vessels

Repair is selective on extent of injury

Recommend repair if all three tibial vessels are injured and there is no flow to the foot (anterior tibial, posterior tibial, and peroneal arteries) [@burkhardt2010]

-   Saphenous vein graft preferred

Recommend ligation if one or two tibial vessels injured, as there is redundant arterial flow to the lower extremity

::: callout-tip
## Take a Look

[Find additional resources for lower artery exposure here.](https://basicmedicalkey.com/surgical-exposure-of-the-lower-extremity-arteries/#:~:text=Exposure%20of%20the%20distal%20portions,and%20stenting%20or%20aortofemoral%20bypass))
:::

## Upper Extremity Arterial Injury and Management

**Important to keep in mind, upper extremity disability can have a significant impact on quality of life.**

Long term functional impairment is measured by the Disabilities of Arm, Should, Hand (DASH) questionnaire. Impairment most closely associated with duration and severity of ischemia and concomitant nerve injury (36%). Open reconstruction is preferred and patency rates are high.[@frech2016]

### Subclavian and Proximal Axillary Arteries

Due to protected anatomic location of subclavian vessels, most subclavian artery trauma is usually cause by penetrating mechanism.

Considered a junctional region for hemorrhage with difficult access for exposure

Endovascular approach with covered stents may be used in traumatic axillo-subclavian injuries that are stable enough for intervention (i.e. do not require a resuscitative thoracotomy) [@xenos2003; @branco2016]

**Exposure**

-   Requires thoracotomy or sternotomy associated with clavicular incision for access

-   Right subclavian/axillary arteries

    -   Median sternotomy with extension to supraclavicular incision

    -   Divide sternocleidomastoid muscle 1 cm above clavicle to expose subclavian vein

    -   Retract vein and divide anterior scalene muscle to expose subclavian artery

    -   Careful to locate and avoid phrenic nerve (traverse laterally over anterior scalene)

    -   Aberrant right subclavian artery directly arises from thoracic aorta (0.5-2%) of population

-   Left subclavian/axillary arteries

    -   Left posterolateral thoracotomy is most optimal, however, requires lateral recumbent positioning

    -   If patient is requiring midline laparotomy for operative management of abdominal trauma, recommend anterolateral thoracotomy in 3rd or 4th intercostal space

        -   Extension with supraclavicular incision or median sternotomy to better expose proximal subclavian

        -   Extension with infraclavicular incision to deltopectoral groove to gain access to proximal axillary artery

**Repair**

-   Primary, patch repair, interposition graft, or bypass dependent on extent of injury after debridement to healthy tissue and follows tenets of avoiding tension and preserving arterial lumen integrity

### Distal Axillary and Brachial Arteries 

Brachial artery is continuation of distal axillary artery

**Repair**

-   Primary Repair can be considered in brachial artery if there is redundancy, lack of tension, injury is focal, and no compromise to arterial lumen.

-   Great saphenous vein preferred over prosthetic for conduit.

-   Ligation should be avoided as upper extremity limb ischemia is highly disabling and morbid

### Radial and Ulnar Artery

**Repair**

-   Ligation can be considered if there is appropriate collateralization from either the radial or ulnar artery into the distal palmar arch

-   If either radial or ulnar injury causes distal hand ischemia, should be repaired

## Extremity Venous Injury and Management

Venous injuries can be selectively repaired. More proximal venous injuries should be repaired, while distal injuries can be ligated.

Primary repair with lateral venorrhaphy can be performed due to higher intrinsic compliance of veins.

### Lower Extremity Venous Injury

Proximal Vessels (popliteal and femoral veins)

-   Ligate if patient unstable, acceptable as damage-control maneuver

-   Repair if patient is stable and not in profound shock

    -   Can consider venous shunts as well

-   Studies confirm that venous repair improves arterial flow in the arterial repair since venous outflow is not impeded [@quan2008; @clouse2007; @rasmussen2022]

-   Even if repair of injured venous vessels thrombose over time, thrombosis occurs slowly and does not lead to pulmonary emboli

### Upper Extremity Venous Injury

All EXCEPT proximal axillary and subclavian vein injuries can be ligated in the upper extremity (ie distal axillary, basilic, cephalic, brachial, veins).

Repair can be performed primarily or with graft (autologous or synthetic)
