# Trauma - Venous {#sec-trauma-venous}

Authors: *Kevin Kniery, Adham Elmously, Nakia Sarad, and Todd Rasmussen*

These trauma episodes were developed in collaboration with [Behind the Knife: The Premier Surgery Podcast](https://behindtheknife.org).

```{r echo=FALSE}

library(embedr)

embed_audio("https://traffic.libsyn.com/audiblebleeding/Trauma_-_Abdominal_Venous_02au.mp3")

```

For relevant images and a more in depth discussion of this topic, please review **Chapter 19: Inferior Vena Cava, Portal and Mesenteric Venous System** in Dr. Rasmussen's 4th Edition of *Rich's Vascular Trauma.*[@fabian2021]

## General Principles

### Anatomy

For the discussion today we will divide the IVC into four segments:

-   Infrarenal

-   Renal/suprarenal

-   Retrohepatic

-   Suprahepatic

We will then discuss management of portal vein and SMV separately.

### Non-operative management

-   Generally well-tolerated due to low pressure system and difficulty of exposure increasing risk of more bleeding

    -   Especially for suprarenal and retrohepatic segments

-   Option for blunt mechanism of injuries

-   If patient is hemodynamically stable and there are no other associated injuries, can consider non-operative management with serial imaging (CT with contrast)

### Hemorrhage Control

-   Pre-operative planning with appropriate resuscitation and blood products available

-   Keep in mind coordination with other surgical teams and anesthesia

-   Patients with abdominal venous injuries likely to be polytrauma patients, approach to assess and repair injuries should be time efficient

-   IVC injuries considered Zone I retroperitoneal hematomas

-   Follow general principles of gaining proximal and distal control

    -   Can use low profile sponge sticks (Kittner sponge stick) or manual pressure

    -   Be prepared to refine where you control as the dissection progresses

-   Immediate control of hemorrhage may require ligation. However, once the field is cleared, coordinate with anesthesia to confirm they are making progress with resuscitation and then evaluate whether the patient can tolerate reconstruction at that time or whether you need to continue to follow damage control principles.

-   Iliac vein injury often able to be accessed by ligating the internal iliac artery and mobilizing the common and external iliac artery. Transection of iliacs should only be used as a last resort if this fails. [@leeIliacVesselInjuries2002]

### Primary repair

-   Option for partial tears without risk of narrowing lumen

    -   Narrowing lumen increases risk of thrombosis and thromboembolism

-   Recommend figure of 8 of 16 to repair with 4-0 prolene suture on SH (small half circle) needle

    -   Larger needles are easier to visualize in cases with high amounts of bleeding

    -   When first suture is placed, recommend lifting on either side of suture with both strands to elevate the defect and maintain tension \>\> improves visualization and placement of subsequent sutures to achieve full thickness bites

### Ligation

-   Well-tolerated really only for infrarenal segment IVC
-   Not a viable option renal/suprarenal, retrohepatic, and suprahepatic IVC due to compromised outflow of vital organ structures (i.e. kidneys and liver)
-   Interposition grafts are not readily performed due to inefficiency of time.

## Infrarenal IVC

### Anatomy

IVC from inferior portions of renal veins to iliac bifurcation

### Non-operative Management

This is a low pressure system and therefore non-operative management can be observed in patients with blunt injuries and hemodynamically stable. However if there is penetrating trauma, or a laparotomy is performed for other reasons, the infrarenal IVC should be explored and repaired.

### Exposure

-   Right medial visceral rotation (Cattell-Braasch maneuver)

-   Exposes in the proximal portion the IVC, inferior renal veins, 4th portion of duodenum, and pancreatic head

-   Be aware of lumbar vessels posteriorly and control with vessel loop or clamp

### Hemorrhage Control

-   Proximal and distal control may not be sufficient as there can be significant bleeding from the many lumbar veins that feed into this area of the vena cava.

### Primary Repair

-   SH needle on 4-0 prolene

-   Avoid luminal narrowing of IVC to prevent thrombosis/thromboembolism

### Ligation

-   Ligation can be tolerated and is appropriate when primary repair narrows lumen or if primary repair cannot be performed due to damage-control nature of operation

-   Empirical 4-compartment fasciotomies of lower extremities is dependent on patient's resuscitation status

-   Recommend fasciotomy if patient received large volumes of fluids/products, continues to be hemodynamically tenuous, anticipate long recovery

## Renal/Suprarenal IVC

### Anatomy

-   2-3 cm of IVC, from renal vein to inferior portion of hepatic veins

-   Includes renal veins and gonadal veins

### Non-operative Management

-   Preferred due to location of injury \>\> similar to retrohepatic and suprahepatic segments

-   Exposure of segment may increase risk of bleeding, increase size of defect, or unroof hemostasis formed

### Exposure

-   Right medial visceral rotation (Cattell-Braasch) and mobilizing liver cephalad

-   Liver mobilization may be required to adequately expose this portion of the IVC as it is below the hepatic veins but posterior to the liver parenchyma.

    -   Divide the attachments of the liver to the diaphragm to be able to move liver cephalad

    -   Caution as there are posterior lumbar veins and other branches that can cause more significant bleeding

### Primary Repair

-   Option if liver mobilization does not increase size of defect/tear

-   Follow principles as described above

### Ligation

-   Not as well tolerated as infrarenal segment due to compromised of outflow to renal veins

## Retrohepatic IVC

### Anatomy

This region is very difficult to access and includes the IVC at the confluence of the hepatic veins.

### Management

Non-operative management is preferred due to the location of injury. **The liver provides hemostasis due to overlying pressure and if liver mobilized, can cause more significant bleeding.**

### Exposure

-   Right medial visceral rotation (Cattell-Braasch) and mobilizing liver cephalad. Mobilizing the liver completely off the diaphragm can allow for better visualization.

### Hemorrhage Control

-   As in the more inferior segments of the IVC, it is important to control venous inflow from the more inferior IVC and lumbar veins.

-   Direct control of the hepatic veins is difficult, so ongoing bleeding may may require Total Hepatic Isolation to locate bleeding behind the liver

    -   Total Hepatic Isolation is accomplished with vascular control of the porta hepatis with a Rommel tourniquet, also known as the Pringle maneuver.

        -   Portal Vein - Accounts for 70-80% of hepatic inflow

        -   Hepatic Artery

-   Finally, you need to control the suprahepatic segment of the IVC under the diaphragm to prevent back bleeding.

-   Other options for bleeding control if total hepatic isolation not successful

    -   Supraceliac aortic clamp

        -   Can be considered if bleeding continues to help identify injury

        -   Last option, usually unsurvivable

-   If vascular control is required for an extended period, then an Atriocaval Shunt (AKA Schrock shunt) may be required to maintain venous return to the right atrium and prevent cardiovascular collapse.[@schrock1968]

    -   Can be accomplished with large chest tube with extra hole cut near base

    -   Chest tube clamped at base and inserted via purse string suture at the right atrial appendage \> advanced to infrarenal IVC

    -   Place Rommel tourniquet below area of suprarenal IVC (above the renal veins and last hole in tube)

    -   Second Rommel tourniquet placed above hepatic veins in intrapericardial IVC

    -   [Click here for an image](https://pbs.twimg.com/media/EXxZTaGXsAIdAiO?format=jpg&name=4096x4096){.uri}

### Primary Repair

-   Careful liver mobilization due to multiple branch points and high risk of tear \> will likely require total hepatic isolation for bleeding control

-   Be careful of timing and patient status. May require packing and resuscitation or atriocaval shunt during repair.

### Ligation

Not as well tolerated due to compromised outflow of both renal and hepatic veins, can cause both kidney and liver ischemia

## Suprahepatic IVC

### Anatomy

Includes phrenic veins and pericardium to right atrium

### Non-operative Management

-   Preferred due to location of injury, difficult to access

-   Liver provides hemostasis due to overlying pressure

-   If liver mobilized, can cause more significant bleeding

### Exposure

Divide xiphoid to open costal margins (approximately 2-3 cm cephalad). Wiley vein retractor may be used to fully mobilize the diaphragm and access the IVC in the chest through the diaphragm from the abdomen.

### Hemorrhage Control

Likely will require total hepatic isolation and atriocaval shunt to fully control bleeding and maintain venous return to the heart.

### Primary Repair

Can consider supraceliac aortic clamp and/or atriocaval shunt if extensive repair is required.

### Ligation

Not as well tolerated due to compromised outflow of both renal and hepatic veins, can cause both kidney and liver ischemia.

## Portal Vein and Superior Mesenteric Vein Injuries

Injuries to portal vein and SMV can be very catastrophic. Non-isolated injury --- usually associated with other injuries (ie pancreatic + celiac vessels).

### Exposure

-   Pringle maneuver to gain control of porta hepatis

-   Division of pancreatic head for better visualization

### Management

-   Resuscitation is key

    -   50% of blood volume is sequestered by splanchnic circulation

    -   Coordination with surgical team and anesthesia to resuscitate appropriately

    -   Consider insensible losses with open abdomen during OR time

-   Repair these injuries if possible

    -   Primary repair

    -   Interposition graft conduits

        -   Great saphenous vein

        -   PTFE

        -   Bovine pericardium

    -   Ligation an option in damage-control (high mortality)

        -   Temporizing measure to prepare for reconstruction once bleeding is controlled
